// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AddFavouriteRequestType.
const (
	AddFavouriteRequestTypeAUDIENCE AddFavouriteRequestType = "AUDIENCE"
	AddFavouriteRequestTypeCHART    AddFavouriteRequestType = "CHART"
	AddFavouriteRequestTypeINSIGHT  AddFavouriteRequestType = "INSIGHT"
)

// Defines values for AssetType.
const (
	AssetTypeAUDIENCE AssetType = "AUDIENCE"
	AssetTypeCHART    AssetType = "CHART"
	AssetTypeINSIGHT  AssetType = "INSIGHT"
)

// Defines values for FavouriteType.
const (
	AUDIENCE FavouriteType = "AUDIENCE"
	CHART    FavouriteType = "CHART"
	INSIGHT  FavouriteType = "INSIGHT"
)

// Defines values for GetV1AssetsTypeIdParamsType.
const (
	Audiences GetV1AssetsTypeIdParamsType = "audiences"
	Charts    GetV1AssetsTypeIdParamsType = "charts"
	Insights  GetV1AssetsTypeIdParamsType = "insights"
)

// AddFavouriteRequest defines model for AddFavouriteRequest.
type AddFavouriteRequest struct {
	AssetId     string                  `json:"assetId"`
	Description *string                 `json:"description,omitempty"`
	Type        AddFavouriteRequestType `json:"type"`
}

// AddFavouriteRequestType defines model for AddFavouriteRequest.Type.
type AddFavouriteRequestType string

// Asset defines model for Asset.
type Asset struct {
	Data              *[]float32 `json:"data,omitempty"`
	Description       *string    `json:"description,omitempty"`
	EstimatedReach    *int       `json:"estimatedReach,omitempty"`
	Id                *string    `json:"id,omitempty"`
	Name              *string    `json:"name,omitempty"`
	OwnerUserId       *string    `json:"ownerUserId,omitempty"`
	PopulationPercent *float32   `json:"populationPercent,omitempty"`
	SampleSize        *int       `json:"sampleSize,omitempty"`
	Text              *string    `json:"text,omitempty"`
	TotalRespondents  *int       `json:"totalRespondents,omitempty"`
	Type              *AssetType `json:"type,omitempty"`
	XAxisTitle        *string    `json:"xAxisTitle,omitempty"`
	YAxisTitle        *string    `json:"yAxisTitle,omitempty"`
}

// AssetType defines model for Asset.Type.
type AssetType string

// Favourite defines model for Favourite.
type Favourite struct {
	Asset       *Asset         `json:"asset,omitempty"`
	Description *string        `json:"description,omitempty"`
	Id          *string        `json:"id,omitempty"`
	Type        *FavouriteType `json:"type,omitempty"`
	UserId      *string        `json:"userId,omitempty"`
}

// FavouriteType defines model for Favourite.Type.
type FavouriteType string

// FavouritePage defines model for FavouritePage.
type FavouritePage struct {
	Items      *[]Favourite `json:"items,omitempty"`
	Limit      *int         `json:"limit,omitempty"`
	Page       *int         `json:"page,omitempty"`
	Total      *int         `json:"total,omitempty"`
	TotalPages *int         `json:"totalPages,omitempty"`
}

// UpdateFavouriteRequest defines model for UpdateFavouriteRequest.
type UpdateFavouriteRequest struct {
	Description *string `json:"description,omitempty"`
}

// GetV1AssetsTypeIdParamsType defines parameters for GetV1AssetsTypeId.
type GetV1AssetsTypeIdParamsType string

// GetV1FavouritesParams defines parameters for GetV1Favourites.
type GetV1FavouritesParams struct {
	// Page Page number (default 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Page size (default 20, max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostV1FavouritesJSONRequestBody defines body for PostV1Favourites for application/json ContentType.
type PostV1FavouritesJSONRequestBody = AddFavouriteRequest

// PatchV1FavouritesIdJSONRequestBody defines body for PatchV1FavouritesId for application/json ContentType.
type PatchV1FavouritesIdJSONRequestBody = UpdateFavouriteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Fetch an asset owned by the authenticated user
	// (GET /v1/assets/{type}/{id})
	GetV1AssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetV1AssetsTypeIdParamsType, id string)
	// List favourites for the authenticated user
	// (GET /v1/favourites)
	GetV1Favourites(w http.ResponseWriter, r *http.Request, params GetV1FavouritesParams)
	// Add a new favourite for the authenticated user
	// (POST /v1/favourites)
	PostV1Favourites(w http.ResponseWriter, r *http.Request)
	// Delete a favourite by ID
	// (DELETE /v1/favourites/{id})
	DeleteV1FavouritesId(w http.ResponseWriter, r *http.Request, id string)
	// Update favourite description
	// (PATCH /v1/favourites/{id})
	PatchV1FavouritesId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch an asset owned by the authenticated user
// (GET /v1/assets/{type}/{id})
func (_ Unimplemented) GetV1AssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetV1AssetsTypeIdParamsType, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List favourites for the authenticated user
// (GET /v1/favourites)
func (_ Unimplemented) GetV1Favourites(w http.ResponseWriter, r *http.Request, params GetV1FavouritesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new favourite for the authenticated user
// (POST /v1/favourites)
func (_ Unimplemented) PostV1Favourites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a favourite by ID
// (DELETE /v1/favourites/{id})
func (_ Unimplemented) DeleteV1FavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update favourite description
// (PATCH /v1/favourites/{id})
func (_ Unimplemented) PatchV1FavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetV1AssetsTypeId operation middleware
func (siw *ServerInterfaceWrapper) GetV1AssetsTypeId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "type" -------------
	var pType GetV1AssetsTypeIdParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", chi.URLParam(r, "type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1AssetsTypeId(w, r, pType, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetV1Favourites operation middleware
func (siw *ServerInterfaceWrapper) GetV1Favourites(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1FavouritesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Favourites(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostV1Favourites operation middleware
func (siw *ServerInterfaceWrapper) PostV1Favourites(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Favourites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteV1FavouritesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FavouritesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1FavouritesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PatchV1FavouritesId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1FavouritesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchV1FavouritesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/assets/{type}/{id}", wrapper.GetV1AssetsTypeId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/favourites", wrapper.GetV1Favourites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/favourites", wrapper.PostV1Favourites)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/favourites/{id}", wrapper.DeleteV1FavouritesId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/favourites/{id}", wrapper.PatchV1FavouritesId)
	})

	return r
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200Response struct {
}

func (response GetHealth200Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetV1AssetsTypeIdRequestObject struct {
	Type GetV1AssetsTypeIdParamsType `json:"type"`
	Id   string                      `json:"id"`
}

type GetV1AssetsTypeIdResponseObject interface {
	VisitGetV1AssetsTypeIdResponse(w http.ResponseWriter) error
}

type GetV1AssetsTypeId200JSONResponse Asset

func (response GetV1AssetsTypeId200JSONResponse) VisitGetV1AssetsTypeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1AssetsTypeId401Response struct {
}

func (response GetV1AssetsTypeId401Response) VisitGetV1AssetsTypeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetV1AssetsTypeId404Response struct {
}

func (response GetV1AssetsTypeId404Response) VisitGetV1AssetsTypeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetV1FavouritesRequestObject struct {
	Params GetV1FavouritesParams
}

type GetV1FavouritesResponseObject interface {
	VisitGetV1FavouritesResponse(w http.ResponseWriter) error
}

type GetV1Favourites200JSONResponse FavouritePage

func (response GetV1Favourites200JSONResponse) VisitGetV1FavouritesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1Favourites401Response struct {
}

func (response GetV1Favourites401Response) VisitGetV1FavouritesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostV1FavouritesRequestObject struct {
	Body *PostV1FavouritesJSONRequestBody
}

type PostV1FavouritesResponseObject interface {
	VisitPostV1FavouritesResponse(w http.ResponseWriter) error
}

type PostV1Favourites201JSONResponse string

func (response PostV1Favourites201JSONResponse) VisitPostV1FavouritesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostV1Favourites400Response struct {
}

func (response PostV1Favourites400Response) VisitPostV1FavouritesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostV1Favourites401Response struct {
}

func (response PostV1Favourites401Response) VisitPostV1FavouritesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteV1FavouritesIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteV1FavouritesIdResponseObject interface {
	VisitDeleteV1FavouritesIdResponse(w http.ResponseWriter) error
}

type DeleteV1FavouritesId204Response struct {
}

func (response DeleteV1FavouritesId204Response) VisitDeleteV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteV1FavouritesId401Response struct {
}

func (response DeleteV1FavouritesId401Response) VisitDeleteV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteV1FavouritesId403Response struct {
}

func (response DeleteV1FavouritesId403Response) VisitDeleteV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type DeleteV1FavouritesId404Response struct {
}

func (response DeleteV1FavouritesId404Response) VisitDeleteV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PatchV1FavouritesIdRequestObject struct {
	Id   string `json:"id"`
	Body *PatchV1FavouritesIdJSONRequestBody
}

type PatchV1FavouritesIdResponseObject interface {
	VisitPatchV1FavouritesIdResponse(w http.ResponseWriter) error
}

type PatchV1FavouritesId204Response struct {
}

func (response PatchV1FavouritesId204Response) VisitPatchV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PatchV1FavouritesId401Response struct {
}

func (response PatchV1FavouritesId401Response) VisitPatchV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PatchV1FavouritesId403Response struct {
}

func (response PatchV1FavouritesId403Response) VisitPatchV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type PatchV1FavouritesId404Response struct {
}

func (response PatchV1FavouritesId404Response) VisitPatchV1FavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Fetch an asset owned by the authenticated user
	// (GET /v1/assets/{type}/{id})
	GetV1AssetsTypeId(ctx context.Context, request GetV1AssetsTypeIdRequestObject) (GetV1AssetsTypeIdResponseObject, error)
	// List favourites for the authenticated user
	// (GET /v1/favourites)
	GetV1Favourites(ctx context.Context, request GetV1FavouritesRequestObject) (GetV1FavouritesResponseObject, error)
	// Add a new favourite for the authenticated user
	// (POST /v1/favourites)
	PostV1Favourites(ctx context.Context, request PostV1FavouritesRequestObject) (PostV1FavouritesResponseObject, error)
	// Delete a favourite by ID
	// (DELETE /v1/favourites/{id})
	DeleteV1FavouritesId(ctx context.Context, request DeleteV1FavouritesIdRequestObject) (DeleteV1FavouritesIdResponseObject, error)
	// Update favourite description
	// (PATCH /v1/favourites/{id})
	PatchV1FavouritesId(ctx context.Context, request PatchV1FavouritesIdRequestObject) (PatchV1FavouritesIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetV1AssetsTypeId operation middleware
func (sh *strictHandler) GetV1AssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetV1AssetsTypeIdParamsType, id string) {
	var request GetV1AssetsTypeIdRequestObject

	request.Type = pType
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1AssetsTypeId(ctx, request.(GetV1AssetsTypeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1AssetsTypeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1AssetsTypeIdResponseObject); ok {
		if err := validResponse.VisitGetV1AssetsTypeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetV1Favourites operation middleware
func (sh *strictHandler) GetV1Favourites(w http.ResponseWriter, r *http.Request, params GetV1FavouritesParams) {
	var request GetV1FavouritesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1Favourites(ctx, request.(GetV1FavouritesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1Favourites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1FavouritesResponseObject); ok {
		if err := validResponse.VisitGetV1FavouritesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostV1Favourites operation middleware
func (sh *strictHandler) PostV1Favourites(w http.ResponseWriter, r *http.Request) {
	var request PostV1FavouritesRequestObject

	var body PostV1FavouritesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostV1Favourites(ctx, request.(PostV1FavouritesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostV1Favourites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostV1FavouritesResponseObject); ok {
		if err := validResponse.VisitPostV1FavouritesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteV1FavouritesId operation middleware
func (sh *strictHandler) DeleteV1FavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteV1FavouritesIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteV1FavouritesId(ctx, request.(DeleteV1FavouritesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteV1FavouritesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteV1FavouritesIdResponseObject); ok {
		if err := validResponse.VisitDeleteV1FavouritesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchV1FavouritesId operation middleware
func (sh *strictHandler) PatchV1FavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	var request PatchV1FavouritesIdRequestObject

	request.Id = id

	var body PatchV1FavouritesIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchV1FavouritesId(ctx, request.(PatchV1FavouritesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchV1FavouritesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchV1FavouritesIdResponseObject); ok {
		if err := validResponse.VisitPatchV1FavouritesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX32/jNgz+VwRuDxtg1M71Hg55y9rrNdvQFf1xeygKVLGYWDdbciW61zTw/z7ISmIn",
	"VrIU7YY91bFo8iO/j6S6gFQXpVaoyMJwATbNsODN40iIM/6kKyMJr/CxQkvudWl0iYYkNkbcWqSxcI80",
	"LxGGYMlINYM6AoE2NbIkqVXw3L9YAKqqgOEdjC+ux1/ObyCC0e3p+PPFyWeI4OR8dHUD99H253UEBh8r",
	"aVC4b5vTaA2ntdeTb5iSCzdyZ/0MBCfu/krCwnZwqqqYoGlxAjeGzw/JCy3JghOKK+Rp1jGRinDmfcpw",
	"yRQvMHigvys0txbNjlqXuqxy7iBdoklRUTATy4syx2v5gmFUhM8UpkoTz6/QllqJlVQCn7+F0AieR8/S",
	"3kjKwyWY7zuuA4Sv1btDtu7hR4NTGMIPcdsG8bIHYi+YAwjfQeYby1HtYntvrpd8Fsh3Le71w77E28IF",
	"1J/LQlKY/3IZO6AMp589Rw51UFShXG9LwQn/eTbtp63v2TUIps7n/NpVwnuZIDdoRhVl7a8zbQpOMIRf",
	"/3R0NnVznvwprD1nRCXUzrFUU92A8Ppt+bJsdDmGCJ7Q2AYoDI6So6Tp+RIVLyUM4fgoOToGV2DKGlBx",
	"hjz3iGZeyC7xpv+dZOAL0rm3cGPSta312XxIkl5p4I/ffPJVUXAzhyH4b1maYfpXcxQ/DeKmZ2y8cLnV",
	"8UKKuhN+0+F1VZbaEArmjC3jBtmDVFbOMrIPEXvglZCoUnQ/uBLsIc24IftwBFE/k6+DphPtzbzEsWjK",
	"YHiBhMbC8G4B0oV0pYHVAF2tg3ZDkKlwSRTv9uQKlNsdK0wQgYcTXDvBeFLsjbbt5D7MSqoVLUc3L8tc",
	"pk0Z4m/WC7j1d8DUqrfnlt9/TCBxmVunr4/JoE/dreIVZdrIFxTe6GPf6EITm+pKiY2macjotsvdvcu0",
	"ldUZUpoxrlgjJeZ2mmCTOaMMmYuKilzOKJibfWvhTde9sk/vXwdtT/U1sonfjRvm1yL7SeCUVzmxwc8Q",
	"eW4fKzTzltxmrHXpLKSShdPPIAoMrGAwK1+wDfUhiVjBn9kgSXYF9WN2Iyp/XkZNkmg/hn9TX5ubJqCz",
	"Sz6TqmGxQ9xhcnuNmH6XljoR2FSbnUJy9yMbkM2lttu6MX6b/KLF/P1aMnCTrjdvsG5i1D3WBq+CsD1l",
	"esycGNzkhY1PPTOBpTBWTzyXgpkV4HdncCQE40zh9w6gfSz2xsF6CQnM0V/zNvk9bd53GT5wf7x5ngeG",
	"pgcjXjF5j/tGZ9pMpBCo3ns2e3SMd7iYzJf6KDn5/2O2use9/o+K+/5NueMWeVBfBsru3f1f2fXoOtx2",
	"vdbelXlacVaZfHl5HcZxrlOeZ9rS8FPyKYH6vv47AAD//2Tl+gs0EAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
