// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AddFavouriteRequestType.
const (
	AddFavouriteRequestTypeAUDIENCE AddFavouriteRequestType = "AUDIENCE"
	AddFavouriteRequestTypeCHART    AddFavouriteRequestType = "CHART"
	AddFavouriteRequestTypeINSIGHT  AddFavouriteRequestType = "INSIGHT"
)

// Defines values for AssetType.
const (
	AssetTypeAUDIENCE AssetType = "AUDIENCE"
	AssetTypeCHART    AssetType = "CHART"
	AssetTypeINSIGHT  AssetType = "INSIGHT"
)

// Defines values for FavouriteType.
const (
	AUDIENCE FavouriteType = "AUDIENCE"
	CHART    FavouriteType = "CHART"
	INSIGHT  FavouriteType = "INSIGHT"
)

// Defines values for GetAssetsTypeIdParamsType.
const (
	Audiences GetAssetsTypeIdParamsType = "audiences"
	Charts    GetAssetsTypeIdParamsType = "charts"
	Insights  GetAssetsTypeIdParamsType = "insights"
)

// AddFavouriteRequest defines model for AddFavouriteRequest.
type AddFavouriteRequest struct {
	AssetId     string                  `json:"assetId"`
	Description *string                 `json:"description,omitempty"`
	Type        AddFavouriteRequestType `json:"type"`
}

// AddFavouriteRequestType defines model for AddFavouriteRequest.Type.
type AddFavouriteRequestType string

// Asset defines model for Asset.
type Asset struct {
	Data              *[]float32 `json:"data,omitempty"`
	Description       *string    `json:"description,omitempty"`
	EstimatedReach    *int       `json:"estimatedReach,omitempty"`
	Id                *string    `json:"id,omitempty"`
	Name              *string    `json:"name,omitempty"`
	OwnerUserId       *string    `json:"ownerUserId,omitempty"`
	PopulationPercent *float32   `json:"populationPercent,omitempty"`
	SampleSize        *int       `json:"sampleSize,omitempty"`
	Text              *string    `json:"text,omitempty"`
	TotalRespondents  *int       `json:"totalRespondents,omitempty"`
	Type              *AssetType `json:"type,omitempty"`
	XAxisTitle        *string    `json:"xAxisTitle,omitempty"`
	YAxisTitle        *string    `json:"yAxisTitle,omitempty"`
}

// AssetType defines model for Asset.Type.
type AssetType string

// Favourite defines model for Favourite.
type Favourite struct {
	Asset       *Asset         `json:"asset,omitempty"`
	Description *string        `json:"description,omitempty"`
	Id          *string        `json:"id,omitempty"`
	Type        *FavouriteType `json:"type,omitempty"`
	UserId      *string        `json:"userId,omitempty"`
}

// FavouriteType defines model for Favourite.Type.
type FavouriteType string

// FavouritePage defines model for FavouritePage.
type FavouritePage struct {
	Items      *[]Favourite `json:"items,omitempty"`
	Limit      *int         `json:"limit,omitempty"`
	Page       *int         `json:"page,omitempty"`
	Total      *int         `json:"total,omitempty"`
	TotalPages *int         `json:"totalPages,omitempty"`
}

// UpdateFavouriteRequest defines model for UpdateFavouriteRequest.
type UpdateFavouriteRequest struct {
	Description *string `json:"description,omitempty"`
}

// GetAssetsTypeIdParamsType defines parameters for GetAssetsTypeId.
type GetAssetsTypeIdParamsType string

// GetFavouritesParams defines parameters for GetFavourites.
type GetFavouritesParams struct {
	// Page Page number (default 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Page size (default 20, max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostFavouritesJSONRequestBody defines body for PostFavourites for application/json ContentType.
type PostFavouritesJSONRequestBody = AddFavouriteRequest

// PatchFavouritesIdJSONRequestBody defines body for PatchFavouritesId for application/json ContentType.
type PatchFavouritesIdJSONRequestBody = UpdateFavouriteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Fetch an asset owned by the authenticated user
	// (GET /assets/{type}/{id})
	GetAssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetAssetsTypeIdParamsType, id string)
	// List favourites for the authenticated user
	// (GET /favourites)
	GetFavourites(w http.ResponseWriter, r *http.Request, params GetFavouritesParams)
	// Add a new favourite for the authenticated user
	// (POST /favourites)
	PostFavourites(w http.ResponseWriter, r *http.Request)
	// Delete a favourite by ID
	// (DELETE /favourites/{id})
	DeleteFavouritesId(w http.ResponseWriter, r *http.Request, id string)
	// Update favourite description
	// (PATCH /favourites/{id})
	PatchFavouritesId(w http.ResponseWriter, r *http.Request, id string)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Fetch an asset owned by the authenticated user
// (GET /assets/{type}/{id})
func (_ Unimplemented) GetAssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetAssetsTypeIdParamsType, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List favourites for the authenticated user
// (GET /favourites)
func (_ Unimplemented) GetFavourites(w http.ResponseWriter, r *http.Request, params GetFavouritesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new favourite for the authenticated user
// (POST /favourites)
func (_ Unimplemented) PostFavourites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a favourite by ID
// (DELETE /favourites/{id})
func (_ Unimplemented) DeleteFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update favourite description
// (PATCH /favourites/{id})
func (_ Unimplemented) PatchFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAssetsTypeId operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsTypeId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "type" -------------
	var pType GetAssetsTypeIdParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", chi.URLParam(r, "type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsTypeId(w, r, pType, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetFavourites operation middleware
func (siw *ServerInterfaceWrapper) GetFavourites(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFavouritesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavourites(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostFavourites operation middleware
func (siw *ServerInterfaceWrapper) PostFavourites(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFavourites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteFavouritesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteFavouritesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFavouritesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PatchFavouritesId operation middleware
func (siw *ServerInterfaceWrapper) PatchFavouritesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchFavouritesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{type}/{id}", wrapper.GetAssetsTypeId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/favourites", wrapper.GetFavourites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/favourites", wrapper.PostFavourites)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/favourites/{id}", wrapper.DeleteFavouritesId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/favourites/{id}", wrapper.PatchFavouritesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

type GetAssetsTypeIdRequestObject struct {
	Type GetAssetsTypeIdParamsType `json:"type"`
	Id   string                    `json:"id"`
}

type GetAssetsTypeIdResponseObject interface {
	VisitGetAssetsTypeIdResponse(w http.ResponseWriter) error
}

type GetAssetsTypeId200JSONResponse Asset

func (response GetAssetsTypeId200JSONResponse) VisitGetAssetsTypeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsTypeId401Response struct {
}

func (response GetAssetsTypeId401Response) VisitGetAssetsTypeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetAssetsTypeId404Response struct {
}

func (response GetAssetsTypeId404Response) VisitGetAssetsTypeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetFavouritesRequestObject struct {
	Params GetFavouritesParams
}

type GetFavouritesResponseObject interface {
	VisitGetFavouritesResponse(w http.ResponseWriter) error
}

type GetFavourites200JSONResponse FavouritePage

func (response GetFavourites200JSONResponse) VisitGetFavouritesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFavourites401Response struct {
}

func (response GetFavourites401Response) VisitGetFavouritesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostFavouritesRequestObject struct {
	Body *PostFavouritesJSONRequestBody
}

type PostFavouritesResponseObject interface {
	VisitPostFavouritesResponse(w http.ResponseWriter) error
}

type PostFavourites201JSONResponse string

func (response PostFavourites201JSONResponse) VisitPostFavouritesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostFavourites400Response struct {
}

func (response PostFavourites400Response) VisitPostFavouritesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostFavourites401Response struct {
}

func (response PostFavourites401Response) VisitPostFavouritesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteFavouritesIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteFavouritesIdResponseObject interface {
	VisitDeleteFavouritesIdResponse(w http.ResponseWriter) error
}

type DeleteFavouritesId204Response struct {
}

func (response DeleteFavouritesId204Response) VisitDeleteFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteFavouritesId401Response struct {
}

func (response DeleteFavouritesId401Response) VisitDeleteFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteFavouritesId403Response struct {
}

func (response DeleteFavouritesId403Response) VisitDeleteFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type DeleteFavouritesId404Response struct {
}

func (response DeleteFavouritesId404Response) VisitDeleteFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PatchFavouritesIdRequestObject struct {
	Id   string `json:"id"`
	Body *PatchFavouritesIdJSONRequestBody
}

type PatchFavouritesIdResponseObject interface {
	VisitPatchFavouritesIdResponse(w http.ResponseWriter) error
}

type PatchFavouritesId204Response struct {
}

func (response PatchFavouritesId204Response) VisitPatchFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PatchFavouritesId401Response struct {
}

func (response PatchFavouritesId401Response) VisitPatchFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PatchFavouritesId403Response struct {
}

func (response PatchFavouritesId403Response) VisitPatchFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type PatchFavouritesId404Response struct {
}

func (response PatchFavouritesId404Response) VisitPatchFavouritesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200Response struct {
}

func (response GetHealth200Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Fetch an asset owned by the authenticated user
	// (GET /assets/{type}/{id})
	GetAssetsTypeId(ctx context.Context, request GetAssetsTypeIdRequestObject) (GetAssetsTypeIdResponseObject, error)
	// List favourites for the authenticated user
	// (GET /favourites)
	GetFavourites(ctx context.Context, request GetFavouritesRequestObject) (GetFavouritesResponseObject, error)
	// Add a new favourite for the authenticated user
	// (POST /favourites)
	PostFavourites(ctx context.Context, request PostFavouritesRequestObject) (PostFavouritesResponseObject, error)
	// Delete a favourite by ID
	// (DELETE /favourites/{id})
	DeleteFavouritesId(ctx context.Context, request DeleteFavouritesIdRequestObject) (DeleteFavouritesIdResponseObject, error)
	// Update favourite description
	// (PATCH /favourites/{id})
	PatchFavouritesId(ctx context.Context, request PatchFavouritesIdRequestObject) (PatchFavouritesIdResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAssetsTypeId operation middleware
func (sh *strictHandler) GetAssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetAssetsTypeIdParamsType, id string) {
	var request GetAssetsTypeIdRequestObject

	request.Type = pType
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsTypeId(ctx, request.(GetAssetsTypeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsTypeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsTypeIdResponseObject); ok {
		if err := validResponse.VisitGetAssetsTypeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFavourites operation middleware
func (sh *strictHandler) GetFavourites(w http.ResponseWriter, r *http.Request, params GetFavouritesParams) {
	var request GetFavouritesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFavourites(ctx, request.(GetFavouritesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFavourites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFavouritesResponseObject); ok {
		if err := validResponse.VisitGetFavouritesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostFavourites operation middleware
func (sh *strictHandler) PostFavourites(w http.ResponseWriter, r *http.Request) {
	var request PostFavouritesRequestObject

	var body PostFavouritesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostFavourites(ctx, request.(PostFavouritesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFavourites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostFavouritesResponseObject); ok {
		if err := validResponse.VisitPostFavouritesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFavouritesId operation middleware
func (sh *strictHandler) DeleteFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteFavouritesIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFavouritesId(ctx, request.(DeleteFavouritesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFavouritesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFavouritesIdResponseObject); ok {
		if err := validResponse.VisitDeleteFavouritesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchFavouritesId operation middleware
func (sh *strictHandler) PatchFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	var request PatchFavouritesIdRequestObject

	request.Id = id

	var body PatchFavouritesIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchFavouritesId(ctx, request.(PatchFavouritesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchFavouritesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchFavouritesIdResponseObject); ok {
		if err := validResponse.VisitPatchFavouritesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTW/jNhD9KwTbQwsIsby7h4VvbrLZuC3SIB/oIQgQWhxb3EqkQo6ycQz992JI25Ji",
	"2nWQtOgpskjNvJn35pFZ8syUldGg0fHRkrssh1L4x7GUp+LR1FYhXMJDDQ7pdWVNBRYV+E3COcCJpEdc",
	"VMBH3KFVes6bhEtwmVUVKqOj6+HFkoOuSz665ZPzq8nXs2ue8PHNyeTL+fEXnvDjs/HlNb9LXn7eJNzC",
	"Q60sSPrWryYbOO1+M/0GGVK6Ma1tVyAFCvqrEErXwanrcgq2xcmFtWJxSF3gUJUCQV6CyPLOFqUR5iGm",
	"irdMixKiC+a7BnvjwO7odWWquhAE6QJsBhqjlThRVgVcqWeIo0J4wjhVBkVxCa4yWq6lEvn8LYQm/Gn8",
	"pNy1wiLegsW+5SZC+Ea9O2RLDz9amPER/2HQjsFgNQODIJgDCN9B5hvbUe9ie2+tF2IeqXcj7s3DvsLb",
	"xkXUX6hSYZz/apU7ogzSz54lQh0VVazWm0oKhH/2pv20bUemAYGMYi6uqBMhyhSEBTuuMW9/nRpbCuQj",
	"/uufRKfvG0UKq3wTOUeseEOBlZ4ZDyLot+XLsfHFhCf8EazzQPnwKD1K/cxXoEWl+Ih/PEqPPnJqMOYe",
	"1MAL2A2WlKgZLJVs6PU8iLpXOL+qq8pYBMlos2PCArtX2ql5ju4+Yfeilgp0BvRDaMnus1xYdPdH3GOw",
	"3lZIifwroB8Kd72oYCI9IitKQLCOj26XXFFCQsnXXrZ25tas0daw6pnojscaEtn4GhFPeAATPQGi+ZTc",
	"m+1lkDvaTL7mAt0f0pT+ZEbjykVFVRUq800YfHNBS228AwykeWkh4ShiElCowhHVn9LhNnE3WtSYG6ue",
	"QYZNn7Y3nRtkM1Nr2dOvJ6Or3Ns7qtTVZSnsgvQHmOVMaOaFxOh4kWy6YJgDo6ygkWoGyciGfOzBbKPZ",
	"jta2BNIqe1sefeg09CwcTuwnCTNRF8iGP/Mk0PpQg120vHpz6TJZKq1Kks4widhGNJlTz9Cm+pAmrBRP",
	"bJimu5IGs+tlFU+rrGma7Mfwb0qr7/cRiV2IudKewA5thyntNTr6XTnsZGAzY3dqiG4pLiKaC+P6qrHB",
	"0X8xcvF+sxi5zTb9WyRZRbPF2fBVEF7ayxYvxxb6rLDJSeAl3eZloh9FoSSza8Dvzt9YSiaYhu8dQPs4",
	"7PvA5uCRUEC4Z/WpPfHvW3IPPDPe7OERowxQ5Cvc9uP2plNjp0pK0O/txwEdEx0apouVNCqB4d+IF2ND",
	"r/+T1r7/NO64wh00kJGmh3D/V24Dug6z3ah+onIQRbhf7jpVz8KO+InSR/nHbwHeJn/4lmU5ZH+FFjuw",
	"j2uN1LZY3VRHg0FhMlHkxuHoc/o55c1d83cAAAD//yYhTO4hEAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
