package httpapi

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/manos/favourites/http/auth"
)

type Server struct {
	favHandler    *FavouritesHandler
	assetsHandler *AssetsHandler
}

func NewServer(favHandler *FavouritesHandler, assetsHandler *AssetsHandler) *Server {
	return &Server{favHandler: favHandler, assetsHandler: assetsHandler}
}

// Implement ServerInterface generated by oapi-codegen
func (s *Server) GetAssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetAssetsTypeIdParamsType, id string) {
	s.assetsHandler.GetAssetsTypeId(w, r, pType, id)
}

func (s *Server) GetFavourites(w http.ResponseWriter, r *http.Request, params GetFavouritesParams) {
	s.favHandler.GetFavourites(w, r, params)
}

func (s *Server) PostFavourites(w http.ResponseWriter, r *http.Request) {
	s.favHandler.PostFavourites(w, r)
}

func (s *Server) DeleteFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	s.favHandler.DeleteFavouritesId(w, r, id)
}

func (s *Server) PatchFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	s.favHandler.PatchFavouritesId(w, r, id)
}

func (s *Server) GetHealth(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

func NewRouter(jwtCfg auth.JWTConfig, favHandler *FavouritesHandler, assetsHandler *AssetsHandler) http.Handler {
	r := chi.NewRouter()

	// Unprotected health
	r.Get("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})

	protected := chi.NewRouter()
	protected.Use(func(next http.Handler) http.Handler {
		return auth.Middleware(jwtCfg)(next)
	})

	server := NewServer(favHandler, assetsHandler)
	protected.Mount("/", HandlerFromMux(server, protected))

	r.Mount("/", protected)

	return r
}
