package httpapi

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/manos/favourites/http/auth"
)

type Server struct {
	favHandler    *FavouritesHandler
	assetsHandler *AssetsHandler
}

func NewServer(favHandler *FavouritesHandler, assetsHandler *AssetsHandler) *Server {
	return &Server{favHandler: favHandler, assetsHandler: assetsHandler}
}

// Implement ServerInterface generated by oapi-codegen
func (s *Server) GetAssetsTypeId(w http.ResponseWriter, r *http.Request, pType GetAssetsTypeIdParamsType, id string) {
	s.assetsHandler.GetAssetsTypeId(w, r, pType, id)
}

func (s *Server) GetFavourites(w http.ResponseWriter, r *http.Request, params GetFavouritesParams) {
	s.favHandler.GetFavourites(w, r, params)
}

func (s *Server) PostFavourites(w http.ResponseWriter, r *http.Request) {
	s.favHandler.PostFavourites(w, r)
}

func (s *Server) DeleteFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	s.favHandler.DeleteFavouritesId(w, r, id)
}

func (s *Server) PatchFavouritesId(w http.ResponseWriter, r *http.Request, id string) {
	s.favHandler.PatchFavouritesId(w, r, id)
}

func (s *Server) GetHealth(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

func NewRouter(jwtCfg auth.JWTConfig, favHandler *FavouritesHandler, assetsHandler *AssetsHandler, enableDocs bool) http.Handler {
	r := chi.NewRouter()

	// Unprotected health
	r.Get("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})

	if enableDocs {
		r.Get("/docs", serveDocs)
		r.Get("/openapi/swagger.yaml", serveSwaggerYAML)
		r.Get("/openapi/swagger.json", serveSwaggerJSON)
	}

	server := NewServer(favHandler, assetsHandler)

	// Protected API routes (JWT required)
	r.Group(func(api chi.Router) {
		api.Use(skipAuthForPaths(jwtCfg, "/health"))
		HandlerFromMux(server, api)
	})

	return r
}

// skipAuthForPaths wraps the JWT middleware but bypasses it for the provided exact paths.
func skipAuthForPaths(jwtCfg auth.JWTConfig, skipPaths ...string) func(http.Handler) http.Handler {
	jwtMW := auth.Middleware(jwtCfg)
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, p := range skipPaths {
				if r.URL.Path == p || strings.HasPrefix(r.URL.Path, p+"/") {
					next.ServeHTTP(w, r)
					return
				}
			}
			jwtMW(next).ServeHTTP(w, r)
		})
	}
}
